[package]
name = "crablangc_span"
version = "0.0.0"
edition = "2021"

[lib]

[dependencies]
crablangc_serialize = { path = "../crablangc_serialize" }
crablangc_macros = { path = "../crablangc_macros" }
crablangc_data_structures = { path = "../crablangc_data_structures" }
crablangc_index = { path = "../crablangc_index" }
crablangc_arena = { path = "../crablangc_arena" }
scoped-tls = "1.0"
unicode-width = "0.1.4"
cfg-if = "1.0"
tracing = "0.1"
sha1 = "0.10.0"
sha2 = "0.10.1"
md5 = { package = "md-5", version = "0.10.0" }
indexmap = { version = "1.9.3" }
