[package]
name = "profiler_builtins"
version = "0.0.0"
edition = "2021"

[lib]
test = false
bench = false
doc = false

[dependencies]
core = { path = "../core" }
compiler_builtins = { version = "0.1.0", features = ['crablangc-dep-of-std'] }

[build-dependencies]
cc = "1.0.69"
