[package]
name = "proc-macro-test"
version = "0.0.0"
publish = false

authors.workspace = true
edition.workspace = true
license.workspace = true
crablang-version.workspace = true

[lib]
doctest = false

[build-dependencies]
cargo_metadata = "0.15.0"

proc-macro-test-impl = { path = "imp", version = "0.0.0" }

# local deps
toolchain.workspace = true
