#!/bin/sh

# Exit if anything fails
set -e

if [ $# -eq 0 ] || [ "$1" = "-h" ] || [ "$1" = "-help" ] || [ "$1" = "--help" ]; then
    echo "
crablang-gdbgui
===========
gdbgui - https://gdbgui.com - is a graphical front-end to GDB
that runs in a browser. This script invokes gdbgui with the CrabLang
pretty printers loaded.

Simple usage  : crablang-gdbgui target/debug/myprog
With arguments: crablang-gdbgui 'target/debug/myprog arg1 arg2...'
  (note the quotes)


Hints
=====
gdbgui won't be able to find the crablang 'main' method automatically, so
in its options make sure to disable the 'Add breakpoint to main after
loading executable' setting to avoid a 'File not found: main' warning
on startup.

Instead, type 'main' into gdbgui's file browser and you should get
auto-completion on the filename. Just pick 'main.rs', add a breakpoint
by clicking in the line number gutter, and type 'r' or hit the Restart
icon to start your program running.
"
    exit 0
fi

# Prefer crablangc in the same directory as this script
DIR="$(dirname "$0")"
if [ -x "$DIR/crablangc" ]; then
  CRABLANGC="$DIR/crablangc"
else
  CRABLANGC="crablangc"
fi

# Find out where the pretty printer Python module is
CRABLANGC_SYSROOT="$("$CRABLANGC" --print=sysroot)"
GDB_PYTHON_MODULE_DIRECTORY="$CRABLANGC_SYSROOT/lib/crablanglib/etc"
# Get the commit hash for path remapping
CRABLANGC_COMMIT_HASH="$("$CRABLANGC" -vV | sed -n 's/commit-hash: \(\w*\)/\1/p')"

# Set the environment variable `CRABLANG_GDB` to overwrite the call to a
# different/specific command (defaults to `gdb`).
CRABLANG_GDB="${CRABLANG_GDB:-gdb}"

# Set the environment variable `CRABLANG_GDBGUI` to overwrite the call to a
# different/specific command (defaults to `gdbgui`).
CRABLANG_GDBGUI="${CRABLANG_GDBGUI:-gdbgui}"

# These arguments get passed through to GDB and make it load the
# CrabLang pretty printers.
GDB_ARGS="--directory=\"$GDB_PYTHON_MODULE_DIRECTORY\"" \
   "-iex \"add-auto-load-safe-path $GDB_PYTHON_MODULE_DIRECTORY\"" \
   "-iex \"set substitute-path /crablangc/$CRABLANGC_COMMIT_HASH $CRABLANGC_SYSROOT/lib/crablanglib/src/crablang\""

# Finally we execute gdbgui.
PYTHONPATH="$PYTHONPATH:$GDB_PYTHON_MODULE_DIRECTORY" \
  exec ${CRABLANG_GDBGUI} \
  --gdb-cmd "${CRABLANG_GDB} ${GDB_ARGS}" \
  "${@}"

