[package]
name = "stdx"
version = "0.0.0"
description = "TBD"

authors.workspace = true
edition.workspace = true
license.workspace = true
crablang-version.workspace = true

[lib]
doctest = false

[dependencies]
libc = "0.2.135"
backtrace = { version = "0.3.65", optional = true }
always-assert = { version = "0.1.2", features = ["log"] }
# Think twice before adding anything here

[target.'cfg(windows)'.dependencies]
miow = "0.5.0"
winapi = { version = "0.3.9", features = ["winerror"] }

[features]
# Uncomment to enable for the whole crate graph
# default = [ "backtrace" ]
