[package]
name = "base-db"
version = "0.0.0"
description = "TBD"

authors.workspace = true
edition.workspace = true
license.workspace = true
crablang-version.workspace = true

[lib]
doctest = false

[dependencies]
salsa = "0.17.0-pre.2"
crablangc-hash = "1.1.0"

# local deps
cfg.workspace = true
profile.workspace = true
stdx.workspace = true
syntax.workspace = true
test-utils.workspace = true
tt.workspace = true
vfs.workspace = true
