[package]
name = "crablangdoc-json-types"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
crablangc-hash = "1.1.0"

[dev-dependencies]
serde_json = "1.0"
