[package]
name = "syntax"
version = "0.0.0"
description = "Comment and whitespace preserving parser for the Rust language"
repository = "https://github.com/rust-lang/rust-analyzer"

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
cov-mark = "2.0.0-pre.1"
either = "1.7.0"
itertools = "0.10.5"
rowan = "0.15.11"
rustc-hash = "1.1.0"
once_cell = "1.17.0"
indexmap = "2.0.0"
smol_str.workspace = true
triomphe.workspace = true

rustc_lexer.workspace = true

parser.workspace = true
profile.workspace = true
stdx.workspace = true
text-edit.workspace = true

[dev-dependencies]
rayon = "1.6.1"
expect-test = "1.4.0"
proc-macro2 = "1.0.47"
quote = "1.0.20"
ungrammar = "1.16.1"

test-utils.workspace = true
sourcegen.workspace = true

[features]
in-rust-tree = []
