[package]
name = "rustc_driver"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
rustc_driver_impl = { path = "../rustc_driver_impl" }
# FIXME(Nilstrieb): 0.37.12 adds eventfd support for FreeBSD,
# but FreeBSD 12 does not support it: https://github.com/bytecodealliance/rustix/issues/716
rustix = "=0.37.11"
