[package]
authors = ["bjorn3 <bjorn3@users.noreply.github.com>"]
name = "sysroot"
version = "0.0.0"

[dependencies]
core = { path = "./sysroot_src/library/core" }
compiler_builtins = "0.1"
alloc = { path = "./sysroot_src/library/alloc" }
std = { path = "./sysroot_src/library/std", features = ["panic_unwind", "backtrace"] }
test = { path = "./sysroot_src/library/test" }

[patch.crates-io]
crablangc-std-workspace-core = { path = "./sysroot_src/library/crablangc-std-workspace-core" }
crablangc-std-workspace-alloc = { path = "./sysroot_src/library/crablangc-std-workspace-alloc" }
crablangc-std-workspace-std = { path = "./sysroot_src/library/crablangc-std-workspace-std" }

[profile.release]
debug = true
