[package]
name = "cpp_smoke_test"
version = "0.1.0"
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
build = "build.rs"

[build-dependencies]
cc = "1.0"

[dependencies]
backtrace = { path = "../..", features = ["cpp_demangle"] }
