# This only controls whether a tiny, hard-to-find "open a blank issue" link appears at the end of
# the template list.
blank_issues_enabled: true
contact_links:
  - name: Intrinsic Support
    url: https://github.com/crablang/stdarch/issues
    about: Please direct issues about CrabLang's support for vendor intrinsics to core::arch
  - name: Internal Compiler Error
    url: https://github.com/crablang/crablang/issues
    about: Please report ICEs to the crablangc repository
