[package]
name = "error_index_generator"
version = "0.0.0"
edition = "2021"

[dependencies]
mdbook = { version = "0.4", default-features = false, features = ["search"] }
crablangc_error_codes = { version = "0.0.0", path = "../../../compiler/crablangc_error_codes" }

[[bin]]
name = "error_index_generator"
path = "main.rs"
