[package]
name = "stdarch-verify"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2021"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }

[lib]
proc-macro = true
test = false

[dev-dependencies]
serde = { version = "1.0", features = ['derive'] }
serde-xml-rs = "0.6"
serde_json = "1.0.96"
