[package]
name = "rustc_serialize"
version = "0.0.0"
edition = "2021"

[dependencies]
indexmap = "2.0.0"
smallvec = { version = "1.8.1", features = ["union", "may_dangle"] }
thin-vec = "0.2.12"

[dev-dependencies]
rustc_macros = { path = "../rustc_macros" }
tempfile = "3.2"
