name: Abi-cafe

on:
  - push

jobs:
  abi_cafe:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.os }}-${{ matrix.env.TARGET_TRIPLE }}
      cancel-in-progress: true

    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            env:
              TARGET_TRIPLE: x86_64-unknown-linux-gnu
          - os: macos-latest
            env:
              TARGET_TRIPLE: x86_64-apple-darwin
          - os: windows-latest
            env:
              TARGET_TRIPLE: x86_64-pc-windows-msvc
          - os: windows-latest
            env:
              TARGET_TRIPLE: x86_64-pc-windows-gnu

    steps:
    - uses: actions/checkout@v3

    - name: Cache cargo target dir
      uses: actions/cache@v3
      with:
        path: build/cg_clif
        key: ${{ runner.os }}-${{ matrix.env.TARGET_TRIPLE }}-cargo-build-target-${{ hashFiles('crablang-toolchain', '**/Cargo.lock') }}

    - name: Set MinGW as the default toolchain
      if: matrix.env.TARGET_TRIPLE == 'x86_64-pc-windows-gnu'
      run: crablangup set default-host x86_64-pc-windows-gnu

    - name: Use sparse cargo registry
      run: |
        cat >> ~/.cargo/config.toml <<EOF
        [unstable]
        sparse-registry = true
        EOF

    - name: Prepare dependencies
      run: ./y.rs prepare

    - name: Build
      run: ./y.rs build --sysroot none

    - name: Test abi-cafe
      env:
        TARGET_TRIPLE: ${{ matrix.env.TARGET_TRIPLE }}
      run: ./y.rs abi-cafe
