name: Various crablangc tests

on:
  - push

jobs:
  bootstrap_crablangc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache cargo target dir
      uses: actions/cache@v3
      with:
        path: build/cg_clif
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('crablang-toolchain', '**/Cargo.lock') }}

    - name: Use sparse cargo registry
      run: |
        cat >> ~/.cargo/config.toml <<EOF
        [unstable]
        sparse-registry = true
        EOF

    - name: Prepare dependencies
      run: ./y.rs prepare

    - name: Test
      run: ./scripts/test_bootstrap.sh
  crablangc_test_suite:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache cargo target dir
      uses: actions/cache@v3
      with:
        path: build/cg_clif
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('crablang-toolchain', '**/Cargo.lock') }}

    - name: Use sparse cargo registry
      run: |
        cat >> ~/.cargo/config.toml <<EOF
        [unstable]
        sparse-registry = true
        EOF

    - name: Prepare dependencies
      run: ./y.rs prepare

    - name: Test
      run: ./scripts/test_crablangc_tests.sh
