[package]
name = "ide-ssr"
version = "0.0.0"
description = "Structural search and replace of CrabLang code"
repository = "https://github.com/crablang/crablang-analyzer"

authors.workspace = true
edition.workspace = true
license.workspace = true
crablang-version.workspace = true

[lib]
doctest = false

[dependencies]
cov-mark = "2.0.0-pre.1"
itertools = "0.10.5"

# local deps
hir.workspace = true
ide-db.workspace = true
parser.workspace = true
stdx.workspace = true
syntax.workspace = true
text-edit.workspace = true

[dev-dependencies]
expect-test = "1.4.0"

# local deps
test-utils.workspace = true
