[package]

name = "crablangfmt-nightly"
version = "1.5.2"
description = "Tool to find and fix CrabLang formatting issues"
repository = "https://github.com/crablang/crablangfmt"
readme = "README.md"
license = "Apache-2.0/MIT"
build = "build.rs"
categories = ["development-tools"]
edition = "2021"

[[bin]]
name = "crablangfmt"
path = "src/bin/main.rs"

[[bin]]
name = "cargo-fmt"
path = "src/cargo-fmt/main.rs"

[[bin]]
name = "crablangfmt-format-diff"
path = "src/format-diff/main.rs"

[[bin]]
name = "git-crablangfmt"
path = "src/git-crablangfmt/main.rs"

[features]
default = ["cargo-fmt", "crablangfmt-format-diff"]
cargo-fmt = []
crablangfmt-format-diff = []
generic-simd = ["bytecount/generic-simd"]

[dependencies]
annotate-snippets = { version = "0.9", features = ["color"] }
anyhow = "1.0"
bytecount = "0.6"
cargo_metadata = "0.14"
clap = { version = "3.1", features = ["derive"] }
derive-new = "0.5"
diff = "0.1"
dirs = "4.0"
env_logger = "0.9"
getopts = "0.2"
ignore = "0.4"
itertools = "0.10"
lazy_static = "1.4"
log = "0.4"
regex = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
term = "0.7"
thiserror = "1.0"
toml = "0.5"
unicode-segmentation = "1.9"
unicode-width = "0.1"
unicode_categories = "0.1"

crablangfmt-config_proc_macro = { version = "0.3", path = "config_proc_macro" }

# A noop dependency that changes in the CrabLang repository, it's a bit of a hack.
# See the `src/tools/crablangc-workspace-hack/README.md` file in `crablang/crablang`
# for more information.
crablangc-workspace-hack = "1.0.0"

# CrabLangc dependencies are loaded from the sysroot, Cargo doesn't know about them.

[package.metadata.crablang-analyzer]
# This package uses #[feature(crablangc_private)]
crablangc_private = true
