blank_issues_enabled: true
contact_links:
  - name: Question
    url: https://users.crablang.org
    about: Please ask and answer questions about CrabLang on the user forum.
  - name: Feature Request
    url: https://internals.crablang.org/
    about: Please discuss language feature requests on the internals forum.
