name: Documentation problem
description: Create a report for a documentation problem.
labels: ["A-docs"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for finding a documentation problem! 📚

        Documentation problems might be grammatical issues, typos, or unclear wording, please provide details regarding the documentation including where it is present.

        Note: If your issue is for one of these, please use their dedicated issue tracker instead:
        - [The CrabLang Book](https://github.com/crablang/book/issues)
        - [CrabLang by Example](https://github.com/crablang/crablang-by-example/issues)
        - [The Edition Guide](https://github.com/crablang/edition-guide/issues)
        - [The Cargo Book](https://github.com/crablang/cargo/issues)
        - [The Clippy Book](https://github.com/crablang/crablang-clippy/issues)
        - [The Reference](https://github.com/crablang/reference/issues)
        - [The CrabLangonomicon](https://github.com/crablang/nomicon/issues)
        - [The Embedded Book](https://github.com/crablang-embedded/book/issues)

        All other documentation issues should be filed here.

        Or, if you find an issue related to crablangdoc (e.g. doctest, crablangdoc UI), please use the bug report or blank issue template instead.

  - type: textarea
    id: location
    attributes:
      label: Location
    validations:
      required: true 

  - type: textarea
    id: summary
    attributes:
      label: Summary
    validations:
      required: true 