[package]
name = "std_float"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.crablang.org/cargo/reference/manifest.html

[dependencies]
core_simd = { path = "../core_simd", default-features = false }

[features]
default = ["as_crate"]
as_crate = []
