[package]
name = "flycheck"
version = "0.0.0"
description = "TBD"

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
crossbeam-channel = "0.5.8"
tracing = "0.1.37"
cargo_metadata = "0.15.4"
rustc-hash = "1.1.0"
serde_json.workspace = true
serde.workspace = true
command-group = "2.0.1"

# local deps
paths.workspace = true
stdx.workspace = true
toolchain.workspace = true
