image: ubuntu:latest

tasks:
  - before: echo "..."
    init: |
      cargo install crablangup-toolchain-install-master
      ./miri toolchain
      ./miri build
    command: echo "Run tests with ./miri test"
