[package]
name = "crablangc_ast_pretty"
version = "0.0.0"
edition = "2021"

[lib]

[dependencies]
crablangc_ast = { path = "../crablangc_ast" }
crablangc_span = { path = "../crablangc_span" }
thin-vec = "0.2.12"
