[book]
title = "The CrabLang Style Guide"
author = "The CrabLang Style Team"
multilingual = false
src = "src"

[output.html]
git-repository-url = "https://github.com/crablang/crablang/tree/HEAD/src/doc/style-guide/"
