[package]
name = "crablangdoc"
version = "0.0.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
arrayvec = { version = "0.7", default-features = false }
askama = { version = "0.12", default-features = false, features = ["config"] }
itertools = "0.10.1"
minifier = "0.2.2"
once_cell = "1.10.0"
regex = "1"
crablangdoc-json-types = { path = "../crablangdoc-json-types" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
smallvec = "1.8.1"
tempfile = "3"
tracing = "0.1"
tracing-tree = "0.2.0"
threadpool = "1.8.1"

[dependencies.tracing-subscriber]
version = "0.3.3"
default-features = false
features = ["fmt", "env-filter", "smallvec", "parking_lot", "ansi"]

[dev-dependencies]
expect-test = "1.4.0"

[features]
jemalloc = []

[package.metadata.crablang-analyzer]
crablangc_private = true
