[package]
name = "crablangc_serialize"
version = "0.0.0"
edition = "2021"

[dependencies]
indexmap = "1.9.3"
smallvec = { version = "1.8.1", features = ["union", "may_dangle"] }
thin-vec = "0.2.12"

[dev-dependencies]
crablangc_macros = { path = "../crablangc_macros" }
