[package]
name = "ide-completion"
version = "0.0.0"
description = "TBD"

authors.workspace = true
edition.workspace = true
license.workspace = true
crablang-version.workspace = true

[lib]
doctest = false

[dependencies]
cov-mark = "2.0.0-pre.1"
itertools = "0.10.5"

once_cell = "1.17.0"
smallvec.workspace = true


# local deps
base-db.workspace = true
ide-db.workspace = true
profile.workspace = true
stdx.workspace = true
syntax.workspace = true
text-edit.workspace = true
# completions crate should depend only on the top-level `hir` package. if you need
# something from some `hir-xxx` subpackage, reexport the API via `hir`.
hir.workspace = true

[dev-dependencies]
expect-test = "1.4.0"

# local deps
test-utils.workspace = true
