name: Fuzz
on:
  schedule:
    # Once a week
    - cron: '0 0 * * 0'
  push:
    paths:
    - '.github/workflows/fuzz.yml'
  # Allow manual trigger
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CI: 1
  CRABLANG_BACKTRACE: short
  CRABLANGFLAGS: "-D warnings -W unreachable-pub -W bare-trait-objects"
  CRABLANGUP_MAX_RETRIES: 10

jobs:
  crablang:
    if: ${{ github.repository == 'crablang/crablang-analyzer' || github.event.action == 'workflow_dispatch' }}
    name: CrabLang
    runs-on: ubuntu-latest
    env:
      CC: deny_c

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 1

      - name: Install CrabLang toolchain
        run: |
          crablangup install --profile minimal nightly

      - name: Build fuzzers
        run: |
          cargo install cargo-fuzz
          cd crates/syntax
          cargo +nightly fuzz build
