[package]
name = "paths"
version = "0.0.0"
description = "TBD"

authors.workspace = true
edition.workspace = true
license.workspace = true
crablang-version.workspace = true

[lib]
doctest = false

[dependencies]
# Adding this dep sadly puts a lot of crablang-analyzer crates after the
# serde-derive crate. Even though we don't activate the derive feature here,
# someone else in the crate graph certainly does!
# serde = "1"
