[package]
name = "proc-macro-srv-cli"
version = "0.0.0"
description = "TBD"

authors.workspace = true
edition.workspace = true
license.workspace = true
crablang-version.workspace = true

[dependencies]
proc-macro-srv.workspace = true

[features]
sysroot-abi = ["proc-macro-srv/sysroot-abi"]

[[bin]]
name = "crablang-analyzer-proc-macro-srv"
path = "src/main.rs"
