[package]
name = "project-model"
version = "0.0.0"
description = "TBD"

authors.workspace = true
edition.workspace = true
license.workspace = true
crablang-version.workspace = true

[lib]
doctest = false

[dependencies]
tracing = "0.1.35"
crablangc-hash = "1.1.0"
cargo_metadata = "0.15.0"
semver = "1.0.14"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.86"
anyhow = "1.0.62"
la-arena = { version = "0.3.0", path = "../../lib/la-arena" }

# local deps
base-db.workspace = true
cfg.workspace = true
paths.workspace = true
profile.workspace = true
stdx.workspace = true
toolchain.workspace = true

[dev-dependencies]
expect-test = "1.4.0"
