[relabel]
allow-unauthenticated = [
    "A-*", "C-*", "E-*", "I-*", "L-*", "P-*", "S-*", "T-*",
    "good-first-issue", "beta-nominated"
]

# Allows shortcuts like `@crablangbot ready`
#
# See https://github.com/crablang/triagebot/wiki/Shortcuts
[shortcut]

[autolabel."S-waiting-on-review"]
new_pr = true

[assign]
contributing_url = "https://github.com/crablang/crablang-clippy/blob/master/CONTRIBUTING.md"

[assign.owners]
"/.github" = ["@flip1995"]
"/util/gh-pages" = ["@xFrednet"]
"*" = [
    "@flip1995",
    "@Manishearth",
    "@llogiq",
    "@giraffate",
    "@xFrednet",
    "@Alexendoo",
    "@dswij",
    "@Jarcho",
]
