[package]
name = "cargo-credential"
version = "0.2.0"
edition.workspace = true
license.workspace = true
repository = "https://github.com/rust-lang/cargo"
description = "A library to assist writing Cargo credential helpers."

[dependencies]
