[package]
name = "cfg"
version = "0.0.0"
description = "TBD"

authors.workspace = true
edition.workspace = true
license.workspace = true
crablang-version.workspace = true

[lib]
doctest = false

[dependencies]
crablangc-hash = "1.1.0"

# locals deps
tt.workspace = true

[dev-dependencies]
expect-test = "1.4.0"
oorandom = "11.1.3"
# We depend on both individually instead of using `features = ["derive"]` to microoptimize the
# build graph: if the feature was enabled, syn would be built early on in the graph if `smolstr`
# supports `arbitrary`. This way, we avoid feature unification.
arbitrary = "1.2.2"
derive_arbitrary = "1.2.2"

# local deps
mbe.workspace = true
syntax.workspace = true
