[package]
name = "sysroot"
version = "0.0.0"

[dependencies]
core = { path = "./sysroot_src/library/core" }
alloc = { path = "./sysroot_src/library/alloc" }
std = { path = "./sysroot_src/library/std", features = ["panic_unwind", "backtrace"] }
test = { path = "./sysroot_src/library/test" }

compiler_builtins = { version = "0.1.87", default-features = false, features = ["no-asm"] }

[patch.crates-io]
crablangc-std-workspace-core = { path = "./sysroot_src/library/crablangc-std-workspace-core" }
crablangc-std-workspace-alloc = { path = "./sysroot_src/library/crablangc-std-workspace-alloc" }
crablangc-std-workspace-std = { path = "./sysroot_src/library/crablangc-std-workspace-std" }

[profile.dev]
lto = "off"

[profile.release]
debug = true
incremental = true
lto = "off"

# Mandatory for correctly compiling compiler-builtins
[profile.dev.package.compiler_builtins]
debug-assertions = false
overflow-checks = false
codegen-units = 10000

[profile.release.package.compiler_builtins]
debug-assertions = false
overflow-checks = false
codegen-units = 10000
