[package]
name = "crablangbook"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
clap = "4.0.32"
env_logger = "0.10"

[dependencies.mdbook]
version = "0.4.28"
default-features = false
features = ["search"]
