[package]
name = "crablangc_session"
version = "0.0.0"
edition = "2021"

[dependencies]
getopts = "0.2"
crablangc_macros = { path = "../crablangc_macros" }
tracing = "0.1"
crablangc_errors = { path = "../crablangc_errors" }
crablangc_feature = { path = "../crablangc_feature" }
crablangc_hir = { path = "../crablangc_hir" }
crablangc_target = { path = "../crablangc_target" }
crablangc_serialize = { path = "../crablangc_serialize" }
crablangc_data_structures = { path = "../crablangc_data_structures" }
crablangc_index = { path = "../crablangc_index" }
crablangc_span = { path = "../crablangc_span" }
crablangc_fs_util = { path = "../crablangc_fs_util" }
crablangc_ast = { path = "../crablangc_ast" }
crablangc_lint_defs = { path = "../crablangc_lint_defs" }
smallvec = "1.8.1"
termize = "0.1.1"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies.windows]
version = "0.46.0"
features = [
    "Win32_Foundation",
    "Win32_System_LibraryLoader",
]
