[package]
name = "clippy_utils"
version = "0.1.70"
edition = "2021"
publish = false

[dependencies]
arrayvec = { version = "0.7", default-features = false }
if_chain = "1.0"
itertools = "0.10.1"
crablangc-semver = "1.1"

[features]
deny-warnings = []
internal = []

[package.metadata.crablang-analyzer]
# This crate uses #[feature(crablangc_private)]
crablangc_private = true
