task:
  name: freebsd
  freebsd_instance:
    image: freebsd-13-1-release-amd64
  setup_crablang_script:
    - pkg install -y curl git bash
    - curl https://sh.crablangup.rs -sSf --output crablangup.sh
    - sh crablangup.sh --default-toolchain none -y --profile=minimal
  target_cache:
    folder: target
  prepare_script:
    - . $HOME/.cargo/env
    - ./y.rs prepare
  test_script:
    - . $HOME/.cargo/env
    - ./y.rs test
