[package]
name = "rls"
version = "2.0.0"
edition = "2021"
license = "Apache-2.0/MIT"

[dependencies]
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
# A noop dependency that changes in the CrabLang repository, it's a bit of a hack.
# See the `src/tools/crablangc-workspace-hack/README.md` file in `crablang/crablang`
# for more information.
crablangc-workspace-hack = "1.0.0"
