[package]
authors = ["The CrabLang Project Developers"]
name = "installer"
version = "0.0.0"
edition = "2018"

[[bin]]
doc = false
name = "crablang-installer"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.19"
flate2 = "1.0.1"
rayon = "1.0"
tar = "0.4.38"
walkdir = "2"
xz2 = "0.1.4"
num_cpus = "1"
remove_dir_all = "0.5"

[dependencies.clap]
features = ["derive"]
version = "3.1"

[target."cfg(windows)".dependencies]
lazy_static = "1"
winapi = { version = "0.3", features = ["errhandlingapi", "handleapi", "ioapiset", "winerror", "winioctl", "winnt"] }
