[package]
name = "crablangc_baked_icu_data"
version = "0.0.0"
edition = "2021"

[dependencies]
icu_list = "1.1.0"
icu_locid = "1.1.0"
icu_provider = "1.1.0"
icu_provider_adapters = "1.1.0"
zerovec = "0.9.2"

[features]
crablangc_use_parallel_compiler = ['icu_provider/sync']
